### PR TITLE
Use graphviz for layout

### PR DESCRIPTION
**Pull request by awentzonline**
Cool idea to visualize ClickVenture stories. I found that using PyGraphViz works really well out of the box for this. My editor mangled the PR a little so you probably don't want to directly pull this, but the gist is you change `nx.draw_spring` to `nx.draw_graphviz`. Play around with the `prog` parameter for different layouts.

### CODE REVIEW

**Comment by davidasilva** [comment]
Awesome, this is great! Interestingly, this now shows some disconnected components of the graph that definitely shouldn't be there. Time to figure out why the code didn't pick up those connections.

**Comment by awentzonline** [comment]
Wild guess but maybe those disconnected graphs are non-"return to checkpoint" paths from a "finish" node. In other words, sometimes there are meaningful outbound links on finish nodes whereas this script, if I'm not missing anything, seems to not process the finish nodes.

**Comment by davidasilva** [comment]
It was partially that. In one of the adventures, it was a path to the epilogue which used a different div class for the path link in the DOM, so my code didn't pick it up. In the rest, it wasn't an epilogue, but a similar problem involving different div class tags that didn't get picked up. I corrected the latter, but have left the epilogue disconnected for now. I might want to draw those (and the checkpoint links) in a different color/style to distinguish them.

**Comment by awentzonline** [comment]
Cool. I'll keep an eye out for updates.

**Pull request merged**
